# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215d84acbbceef78cf7b18098defc845e37d1019be546ef38d3b7c29b318e503761d6e05e9c261430df773325f3729f5dc95eb128a11615b1bed1085fa6b7b5f

test:
  secret_key_base: 382baf033c90981a94c6e1d5f6ad0f34c6ff44aa159f832fbefe60f1203093087c8bbf2835aab5c7d9c37960e6beb9899de611297c7c63b10d0541744020222e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
